import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  problemSidebar: [{type: 'autogenerated', dirName: 'problems'}],
  toolsSidebar: [{type: 'autogenerated', dirName: 'tools'}],
};

export default sidebars;
